=== Team302/2024Crescendo/src/main/deploy/waypoints.dtd
<!ELEMENT waypoints(waypoint*)>

<!ELEMENT waypoint EMPTY>
<!ATTLIST waypoint
            identifier (GRID_WALL_INTERMEDIATE |
                      GRID_COOP_INTERMEDIATE |
                      GRID_HP_INTERMEDIATE |
                      GRID_WALL_COL_ONE |
                      GRID_WALL_COL_TWO |
                      GRID_WALL_COL_THREE |
                      GRID_COOP_COL_ONE |
                      GRID_COOP_COL_TWO |
                      GRID_COOP_COL_THREE |
                      GRID_HP_COL_ONE |
                      GRID_HP_COL_TWO |
                      GRID_HP_COL_THREE) "GRID_WALL_INTERMEDIATE"
            blueXCoordinate CDATA "0.0"
            blueYCoordinate CDATA "0.0"
            blueRotation CDATA "0.0"
            redXCoordinate CDATA "0.0"
            redYCoordinate CDATA "0.0"
            redRotation CDATA "0.0"
>

=== Team302/2024Crescendo/src/main/deploy/waypoints.xml
<?xml version="1.0" encoding="UTF-8"?>  
<!DOCTYPE robot SYSTEM "waypoints.dtd">
<waypoints>
<!--Coordinates have an origin at the bottom left corner of the field (red loading zone)-->
<!--Column one is closest to the spectator wall, column three is closest to loading zone-->
<!--Coordinates are in meters, rotation in degrees-->  
<!-- @TODO: Determine if we need a separate red/blue y coordinate, right now they are the same for each-->  
    <waypoint identifier="GRID_WALL_INTERMEDIATE"
              blueXCoordinate="4.3"
              blueYCoordinate="0.75"
              blueRotation="0.0"
              redXCoordinate="12.35"
              redYCoordinate="0.75"
              redRotation="180.0"/>
    <waypoint identifier="GRID_COOP_INTERMEDIATE"
              blueXCoordinate="5.3"
              blueYCoordinate="2.75"
              blueRotation="0.0"
              redXCoordinate="9.5"
              redYCoordinate="2.75"
              redRotation="180.0"/>
    <waypoint identifier="GRID_HP_INTERMEDIATE"
              blueXCoordinate="4.3"
              blueYCoordinate="4.45"
              blueRotation="0.0"
              redXCoordinate="12.35"
              redYCoordinate="4.45"
              redRotation="180.0"/>
    <waypoint identifier="GRID_WALL_COL_ONE"
              blueXCoordinate="1.95"
              blueYCoordinate="0.5"
              blueRotation="0.0"
              redXCoordinate="14.7"
              redYCoordinate="0.5"
              redRotation="180.0"/>
    <waypoint identifier="GRID_WALL_COL_TWO"
              blueXCoordinate="1.95"
              blueYCoordinate="1.1"
              blueRotation="0.0"
              redXCoordinate="14.7"
              redYCoordinate="1.1"
              redRotation="180.0"/>
    <waypoint identifier="GRID_WALL_COL_THREE"
              blueXCoordinate="1.95"
              blueYCoordinate="1.6"
              blueRotation="0.0"
              redXCoordinate="14.7"
              redYCoordinate="1.6"
              redRotation="180.0"/>
    <waypoint identifier="GRID_COOP_COL_ONE"
              blueXCoordinate="1.95"
              blueYCoordinate="2.2"
              blueRotation="0.0"
              redXCoordinate="14.7"
              redYCoordinate="2.2"
              redRotation="180.0"/>
    <waypoint identifier="GRID_COOP_COL_TWO"
              blueXCoordinate="1.95"
              blueYCoordinate="2.75"
              blueRotation="0.0"
              redXCoordinate="14.7"
              redYCoordinate="2.75"
              redRotation="180.0"/>
    <waypoint identifier="GRID_COOP_COL_THREE"
              blueXCoordinate="1.95"
              blueYCoordinate="3.3"
              blueRotation="0.0"
              redXCoordinate="14.7"
              redYCoordinate="3.3"
              redRotation="180.0"/>
    <waypoint identifier="GRID_HP_COL_ONE"
              blueXCoordinate="1.95"
              blueYCoordinate="3.85"
              blueRotation="0.0"
              redXCoordinate="14.7"
              redYCoordinate="3.85"
              redRotation="180.0"/>
    <waypoint identifier="GRID_HP_COL_TWO"
              blueXCoordinate="1.95"
              blueYCoordinate="4.4"
              blueRotation="0.0"
              redXCoordinate="14.7"
              redYCoordinate="4.4"
              redRotation="180.0"/>
    <waypoint identifier="GRID_HP_COL_THREE"
              blueXCoordinate="1.95"
              blueYCoordinate="5.0"
              blueRotation="0.0"
              redXCoordinate="14.7"
              redYCoordinate="5.0"
              redRotation="180.0"/>
</waypoints>
