=== Team302/2024Crescendo/src/main/deploy/auton/auton.dtd
<!ELEMENT auton (snippet | primitive)* >

<!ELEMENT snippet EMPTY>
<!ATTLIST snippet file CDATA #IMPLIED>

<!ELEMENT primitive EMPTY >
<!ATTLIST primitive 
          id                ( DO_NOTHING | HOLD_POSITION | DRIVE_DISTANCE | DRIVE_TIME | TURN_ANGLE_ABS | TURN_ANGLE_REL |
                              DRIVE_PATH_PLANNER | RESET_POSITION | RESET_POSITION_PATH_PLANNER | VISION_ALIGN )
                            "DO_NOTHING"
       
		  time				CDATA #IMPLIED
          distance		    CDATA "0.0"
          headingOption     CDATA "MAINTAIN"
          heading           CDATA "0.0"
          drivespeed        CDATA "0.0"
          enddrivespeed     CDATA "0.0"
          pathname          CDATA #IMPLIED
          alignmentMethod   ( ROTATE | STRAFE ) "ROTATE"
          pipeline          ( UNKNOWN | OFF | APRIL_TAG | CONE_NODE | CONE | CUBE ) "APRIL_TAG"

          noteManager       ( NOTE_MANAGER_FRONT_INTAKE | NOTE_MANAGER_BACK_INTAKE | NOTE_MANAGER_TRANSFER |
                              NOTE_MANAGER_PLACER | NOTE_MANAGER_ELEVATOR | NOTE_MANAGER_FEEDER |
                              NOTE_MANAGER_LAUNCHER_TOP | NOTE_MANAGER_LAUNCHER_BOTTOM | NOTE_MANAGER_LAUNCHER_ANGLE )
                              "MOTOR_CONTROLLER_USAGE"


          )
>

=== Team302/2024Crescendo/src/main/deploy/auton/UnusedPaths/BlueAmpWing1Center2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>

<primitive id= "RESET_POSITION_PATH_PLANNER"
        pathname= "BlueAmpWing1Center0"
        noteOption="STATE_HOLD_FEEDER"/>

<primitive id= "DRIVE_PATH_PLANNER"
    pathname= "BlueAmpWing1Center0"
    time= "0.5"
noteOption="STATE_HOLD_FEEDER"
/>

<primitive id= "DO_NOTHING"
    pathname= "BlueAmpWing1Center0"
    time= "0.35"
noteOption="STATE_READY"
/>
<!-- visionAligment = "SPEAKER"/> -->

<snippet file= "ShootWhenStopAuto.xml"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BlueAmpWing1Center0_1"
time= "2.5"
noteOption="STATE_FEEDER_INTAKE"
pathgains = "ShortPath"/>
<!--visionAligment = "SPEAKER"/>-->

<snippet file= "ShootWhenStopAuto.xml"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BlueAmpWing1Center1_1B"
time= "5.1"
noteOption="STATE_FEEDER_INTAKE"/>
<!--visionAligment = "SPEAKER"/>-->

<snippet file= "ShootWhenStopAuto.xml"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BlueAmpWing1Center0_1C"
time= "5.6"
noteOption="STATE_PLACER_INTAKE"/>
<!--visionAligment = "SPEAKER"/>-->

</auton>

=== Team302/2024Crescendo/src/main/deploy/auton/RedAmpWing0Center3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>

<primitive id= "RESET_POSITION_PATH_PLANNER"
pathname= "BlueAmpWing0Center1_B"/>

<snippet file= "ShootWhenStopAuto.xml"/>

<snippet file= "AmpCenterRing1.xml"/>

<snippet file= "ShootWhenStopAuto.xml"/>

<snippet file= "AmpCenterRing2.xml"/>

<snippet file= "ShootWhenStopAuto.xml"/>

<snippet file= "AmpCenterRing3.xml"/>

<snippet file= "ShootWhenStopAuto.xml"/>

</auton>

=== Team302/2024Crescendo/src/main/deploy/auton/BlueAmpWing1Center2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>

<primitive id= "RESET_POSITION_PATH_PLANNER"
        pathname= "BlueAmpWing1Center0"
        noteOption="STATE_READY_AUTO_LAUNCH"/>

<primitive id= "DRIVE_PATH_PLANNER"
    pathname= "BlueAmpWing1Center0"
    time= "1.0"
noteOption="STATE_READY_AUTO_LAUNCH"/>
<!-- visionAligment = "SPEAKER"/> -->

<snippet file= "ShootWhenStopAuto.xml"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BlueAmpWing1Center0_1"
time= "1.2"
noteOption="STATE_FEEDER_INTAKE"/>
<!--visionAligment = "SPEAKER"/>-->

<snippet file= "ShootWhenStopAuto.xml"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BlueAmpWing1Center1_1B"
time= "5.1"
noteOption="STATE_FEEDER_INTAKE"/>
<!--visionAligment = "SPEAKER"/>-->

<snippet file= "ShootWhenStopAuto.xml"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BlueAmpWing1Center0_1C"
time= "6.0"
noteOption="STATE_FEEDER_INTAKE"/>
<!--visionAligment = "SPEAKER"/>-->
<primitive id="DO_NOTHING"
time="0.25"
noteOption="STATE_READY_AUTO_LAUNCH"/>

<snippet file= "ShootWhenStopAuto.xml"/>

</auton>

=== Team302/2024Crescendo/src/main/deploy/auton/BluePodiumWing2Center0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>

<primitive id= "RESET_POSITION_PATH_PLANNER"
pathname = "BluePodiumWing2Center0.path"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BluePodiumWing2Center0.path"
time= "0.5"/>
<!--Go forward a bit while adjusting angle-->

<snippet file= "ShootWhenStop.xml"/>
<!--Stops and shoots-->

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BluePodiumWing2Center0.path"
time= "1.0"/>
<!--We go to pick up ring 1 and are assumed to intake at this time-->

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BluePodiumWing2Center0.path"
time= "1.5"/>
<!--We go up to speaker so we can shoot and get closer to ring 2-->

<snippet file = "ShootWhenStop.xml"/>

<primitive id = "DRIVE_PATH_PLANNER"
pathname= "BluePodiumWing2Center0.path"
time= "1.0"/>
<!--We go forward and are assumed to intake the last ring at this time-->

<snippet file = "ShootWhenStop.xml"/>
<!--We shoot our second ring and are done as we are already across the line-->

</auton>

=== Team302/2024Crescendo/src/main/deploy/auton/BlueSubwooferWing2Center1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">

<auton>

<snippet file= "ShootWhenStopManual.xml"/>

<primitive id= "RESET_POSITION_PATH_PLANNER_NO_VISION"
pathname= "BlueSubwooferWing3Center0_A"
time = "10.0"
noteOption="STATE_FEEDER_INTAKE"
visionAligment="NOTE"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BlueSubwooferWing3Center0_B"
time = "10.0"
noteOption="STATE_HOLD_FEEDER"/>

<snippet file= "ShootWhenStopManual.xml"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BlueSubwooferWing3Center0_E"
time = "10.0"
noteOption="STATE_FEEDER_INTAKE"
visionAligment="NOTE"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BlueSubwooferWing3Center0_F"
time = "10.0"
noteOption="STATE_FEEDER_INTAKE"/>

<snippet file= "ShootWhenStopManual.xml"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BlueSubwooferWing2Center1_A"
time = "10.0"
noteOption="STATE_FEEDER_INTAKE"
visionAligment="NOTE"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BlueSubwooferWing2Center1_B"
time = "10.0"
noteOption="STATE_HOLD_FEEDER"/>

<snippet file= "ShootWhenStopManual.xml"/>

</auton>

=== Team302/2024Crescendo/src/main/deploy/auton/BlueWallOneP.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>
    <primitive id="RESET_POSITION"
	            pathname="BlueWallOne1.wpilib.json"
               intake="INTAKE_HOLD"/>
   <!--score preloaded cone-->
    <snippet file="ScoreCone.xml"/>
    <!--drive to charing station-->
    <primitive id="DRIVE_PATH"
               pathname="BlueWallOne1.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="180"
               arm="STARTING_POSITION_ROTATE"
               extender="STARTING_POSITION_EXTEND"
               intake="INTAKE_OFF"
               time="0.8"
               />
    <primitive id="DRIVE_PATH"
               pathname="BlueWallOne4.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="180"
               arm="STARTING_POSITION_ROTATE"
               extender="STARTING_POSITION_EXTEND"
               intake="INTAKE_OFF"
               time="4.0"
               />
    <primitive id="DRIVE_PATH"
               pathname="BlueWallOne2.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="180"
               arm="STARTING_POSITION_ROTATE"
               extender="STARTING_POSITION_EXTEND"
               intake="INTAKE_OFF"
               time="5.0"
               />
    <primitive id="DRIVE_PATH"
               pathname="BlueWallOne3.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="0"
               arm="STARTING_POSITION_ROTATE"
               extender="STARTING_POSITION_EXTEND"
               intake="INTAKE_OFF"
               time="2.0"
               />
    <!--drive onto charging station-->
    <primitive id="DRIVE_PATH"
               pathname="BlueWallOne1Slow.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="0"
               arm="STARTING_POSITION_ROTATE"
               extender="STARTING_POSITION_EXTEND"
               intake="INTAKE_OFF"
               time="3.0"
               />
    <!--auto balance-->
    <primitive id="AUTO_BALANCE"
               arm="STARTING_POSITION_ROTATE"
               extender="STARTING_POSITION_EXTEND"
               intake="INTAKE_OFF"
               time="10.0"
               />
</auton>

=== Team302/2024Crescendo/src/main/deploy/auton/BluePodiumWing3Center1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>

<primitive id= "RESET_POSITION_PATH_PLANNER"
pathname= "BluePodiumWing3Center1_A"/>

<primitive id= "DO_NOTHING"
time= "0.5"
noteOption= "STATE_READY_ODOMETRY_LAUNCH"
headingOption = "FACE_SPEAKER"/>


<snippet file= "ShootWhenStopAuto.xml"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BluePodiumWing3Center1_A"
time = "3.0"
noteOption="STATE_FEEDER_INTAKE"
pathgains = "ShortPath"
visionAligment= "SPEAKER"/>

<snippet file= "ShootWhenStopAuto.xml"/> 

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BluePodiumWing3Center1B"
time = "3.5"
pathUpdateOption = "NOTE"
noteOption="STATE_FEEDER_INTAKE"
/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BluePodiumWing3Center1_C"
time = "3.0"
noteOption="STATE_HOLD_FEEDER"
visionAligment= "SPEAKER"/>

<snippet file= "ShootWhenStopAuto.xml"/> 

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BluePodiumWing3Center1_D"
time = "1.5"
noteOption="STATE_FEEDER_INTAKE"
pathgains = "ShortPath"
visionAligment= "SPEAKER"/>

<snippet file= "ShootWhenStopAuto.xml"/> 


<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BluePodiumWing3Center1_E"
time = "2.0"
noteOption="STATE_FEEDER_INTAKE"
pathgains = "ShortPath"
visionAligment= "SPEAKER"/>

<snippet file= "ShootWhenStopAuto.xml"/> 


</auton>

=== Team302/2024Crescendo/src/main/deploy/auton/BlueWallTwoP.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>
   <primitive id="RESET_POSITION"
	            pathname="BlueWallOne1.wpilib.json"
               intake="INTAKE_HOLD"/>
    <!--score preloaded cone-->
    <snippet file="ScoreCone.xml"/>
    <!--drive to charing station-->
    <primitive id="DRIVE_PATH"
               pathname="BlueWallOne1.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="180"
               arm="STARTING_POSITION_ROTATE"
               extender="STARTING_POSITION_EXTEND"
               intake="INTAKE"
               time="0.8"
               />
    <primitive id="DRIVE_PATH"
               pathname="BlueWallOne4.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="0"
               arm="STARTING_POSITION_ROTATE"
               extender="STARTING_POSITION_EXTEND"
               intake="INTAKE"
               time="1.0"
               />
    <primitive id="DRIVE_PATH"
               pathname="BlueWallOne2Slow.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="0"
               arm="STARTING_POSITION_ROTATE"
               extender="STARTING_POSITION_EXTEND"
               intake="INTAKE"
               time="3.5"
               />
    <primitive id="DRIVE_PATH"
               pathname="BlueWallTwo1.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="0"
               arm="STARTING_POSITION_ROTATE"
               extender="STARTING_POSITION_EXTEND"
               intake="INTAKE"
               time="1.5"
               />
    <!--pick up cube-->
    <primitive id="DO_NOTHING"
               headingOption="SPECIFIED_ANGLE"
               heading="0"
               arm="FLOOR_POSITION_ROTATE_AUTON"
               extender="STARTING_POSITION_EXTEND"
               intake="INTAKE"
               time="1.0"
               />
    <primitive id="DO_NOTHING"
               headingOption="SPECIFIED_ANGLE"
               heading="0"
               arm="FLOOR_POSITION_ROTATE_AUTON"
               extender="FLOOR_EXTEND"
               intake="INTAKE"
               time="0.4"
               />
    <primitive id="DO_NOTHING"
               headingOption="SPECIFIED_ANGLE"
               heading="0"
               arm="FLOOR_POSITION_ROTATE_AUTON"
               extender="FLOOR_EXTEND"
               intake="INTAKE_HOLD"
               time="0.4"
               />
   <!--drive to scoring station-->
    <primitive id="DRIVE_PATH"
               pathname="BlueWallTwo2.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="0"
               arm="HOLD_POSITION_ROTATE"
               extender="STARTING_POSITION_EXTEND"
               intake="INTAKE_HOLD"
               time="3.0"
               />
    <primitive id="DRIVE_PATH"
               pathname="BlueHPOne4Slow.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="0"
               intake="INTAKE_HOLD"               
               time="6.0"
               />
    <primitive id="AUTO_BALANCE"
               headingOption="SPECIFIED_ANGLE"
               heading="180"
               arm="STARTING_POSITION_ROTATE"
               extender="STARTING_POSITION_EXTEND"
               intake="INTAKE_HOLD"
               time="10.0"
               />
</auton>
