=== Team302/2024Crescendo/src/main/deploy/auton/auton.dtd
<!ELEMENT auton (snippet | primitive)* >

<!ELEMENT snippet EMPTY>
<!ATTLIST snippet file CDATA #IMPLIED>

<!ELEMENT primitive EMPTY >
<!ATTLIST primitive 
          id                ( DO_NOTHING | HOLD_POSITION | DRIVE_DISTANCE | DRIVE_TIME | TURN_ANGLE_ABS | TURN_ANGLE_REL |
                              DRIVE_PATH_PLANNER | RESET_POSITION | RESET_POSITION_PATH_PLANNER | VISION_ALIGN )
                            "DO_NOTHING"
       
		  time				CDATA #IMPLIED
          distance		    CDATA "0.0"
          headingOption     CDATA "MAINTAIN"
          heading           CDATA "0.0"
          drivespeed        CDATA "0.0"
          enddrivespeed     CDATA "0.0"
          pathname          CDATA #IMPLIED
          alignmentMethod   ( ROTATE | STRAFE ) "ROTATE"
          pipeline          ( UNKNOWN | OFF | APRIL_TAG | CONE_NODE | CONE | CUBE ) "APRIL_TAG"

          noteManager       ( NOTE_MANAGER_FRONT_INTAKE | NOTE_MANAGER_BACK_INTAKE | NOTE_MANAGER_TRANSFER |
                              NOTE_MANAGER_PLACER | NOTE_MANAGER_ELEVATOR | NOTE_MANAGER_FEEDER |
                              NOTE_MANAGER_LAUNCHER_TOP | NOTE_MANAGER_LAUNCHER_BOTTOM | NOTE_MANAGER_LAUNCHER_ANGLE )
                              "MOTOR_CONTROLLER_USAGE"


          )
>

=== Team302/2024Crescendo/src/main/deploy/auton/BluePodiumWing0Center2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>

  <primitive id= "RESET_POSITION_PATH_PLANNER"
                pathname= "BlueWideWing0Center2_A"
                noteOption="STATE_READY_ODOMETRY_LAUNCH"/>

<primitive id= "DO_NOTHING"
noteOption="STATE_READY_ODOMETRY_LAUNCH" 
time= "0.35"/>

<snippet file= "ShootWhenStopAuto.xml"/>

<primitive id= "DRIVE_PATH_PLANNER" 
pathname= "BlueWideWing0Center2_B"
noteOption= "STATE_FEEDER_INTAKE"
time= "3.0"
pathUpdateOption = "NOTE"/>

<primitive id= "DRIVE_PATH_PLANNER" 
pathname= "BlueWideWing0Center2_C"
noteOption= "STATE_FEEDER_INTAKE"
time= "3.0"/>

<snippet file= "ShootWhenStopAuto.xml"/>

<primitive id= "DRIVE_PATH_PLANNER" 
pathname= "BlueWideWing0Center2_D"
noteOption= "STATE_FEEDER_INTAKE"
pathUpdateOption = "NOTE"
time= "3.2"
/>

<primitive id= "DRIVE_PATH_PLANNER" 
pathname= "BlueWideWing0Center2_E"
noteOption= "STATE_FEEDER_INTAKE"
time= "3.3"/>

<snippet file= "ShootWhenStopAuto.xml"/>

</auton>

=== Team302/2024Crescendo/src/main/deploy/auton/BluePodiumWing2Center2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>

  <primitive id= "RESET_POSITION_PATH_PLANNER"
                pathname= "BluePodiumWing2Center2Start"
                noteOption="STATE_READY_ODOMETRY_LAUNCH"/>

<zone ygrid1="Y_11"
            xgrid1="X_Q"
            ygrid2="Y_13"
            xgrid2="X_S"
            noteOption="STATE_AUTO_LAUNCH_ODOMETRY"/>

<snippet file= "ShootWhenStopAuto"/>

<primitive id= "DRIVE_PATH_PLANNER" 
pathname= "BluePodiumWing2Center2Start"
noteOption= "STATE_READY_AUTO_LAUNCH"
time= "0.5"/>

<snippet file= "ShootWhenStopAuto.xml"/>

<primitive id= "DRIVE_PATH_PLANNER" 
pathname= "BluePodiumWing2Center2_A"
noteOption= "STATE_FEEDER_INTAKE"
time= "2.0"/>

<snippet file= "ShootWhenStopAuto.xml"/>

<primitive id= "DRIVE_PATH_PLANNER" 
pathname= "BluePodiumWing2Center2_B"
noteOption= "STATE_FEEDER_INTAKE"
time= "2.0"/>

<primitive id= "DRIVE_TO_NOTE"
noteOption= "STATE_FEEDER_INTAKE"/>

<primitive id= "DRIVE_PATH_PLANNER" 
pathname= "BluePodiumWing2Center2_C"
noteOption= "STATE_FEEDER_INTAKE"
time= "3.0"/>

<snippet file= "ShootWhenStopAuto.xml"/>

<primitive id= "DRIVE_PATH_PLANNER" 
pathname= "BluePodiumWing2Center2_D"
noteOption= "STATE_FEEDER_INTAKE"
time= "3.0"/>


<primitive id= "DRIVE_PATH_PLANNER" 
pathname= "BluePodiumWing2Center2_E"
noteOption= "STATE_FEEDER_INTAKE"
time= "3.0"/>

<snippet file= "ShootWhenStopAuto.xml"/>

</auton>

=== Team302/2024Crescendo/src/main/deploy/auton/BlueWallThreeNP.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>
    <primitive id="RESET_POSITION"
               pathname="BlueWallOne1.wpilib.json"
               intake="INTAKE_HOLD"/>
    <!--score preloaded cone-->
    <snippet file="ScoreCone.xml"/>
    <!--drive to charing station-->
    <primitive id="DRIVE_PATH"
               pathname="BlueWallOne1.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="180"
               intake="INTAKE"
               time="0.8"
               />
    <primitive id="DRIVE_PATH"
               pathname="BlueWallOne4.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="0"
               intake="INTAKE"
               time="1.0"
               />
    <primitive id="DRIVE_PATH"
               pathname="BlueWallOne2Slow.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="0"
               intake="INTAKE"
               time="3.5"
               />
    <primitive id="DRIVE_PATH"
               pathname="BlueWallTwo1.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="0"
               intake="INTAKE"
               time="1.5"
               />
    <!--pick up cube-->
    <primitive id="DO_NOTHING"
               headingOption="SPECIFIED_ANGLE"
               heading="0"
               intake="INTAKE"
               time="1.0"
               />
    <primitive id="DO_NOTHING"
               headingOption="SPECIFIED_ANGLE"
               heading="0"
               intake="INTAKE"
               time="0.4"
               />
    <primitive id="DO_NOTHING"
               headingOption="SPECIFIED_ANGLE"
               heading="0"
               intake="INTAKE"
               time="0.4"
               />
   <!--drive to scoring station-->
    <primitive id="DRIVE_PATH"
               pathname="BlueWallTwo4.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="180"
               intake="HOLD"
               time="6.0"
               />
   <!--score cube-->
    <primitive id="DO_NOTHING"
               intake="HOLD"
               time="0.6"
               />
    <primitive id="DO_NOTHING"
               intake="HOLD"
               time="0.35"
               />
    <primitive id="DO_NOTHING"
               intake="HOLD"
               time="0.5"
               />
    <primitive id="DO_NOTHING"
               intake="HOLD"
               time="0.5"
               />
   <primitive id="DO_NOTHING"
               intake="INTAKE_RELEASE"
               time="0.5"
               />
</auton>

=== Team302/2024Crescendo/src/main/deploy/auton/RedCOOPTwoPCube.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>
    <primitive id="RESET_POSITION"
	           pathname="RedCOOPOne1CubeSlow.wpilib.json"
               intake="INTAKE_HOLD"/>
    <!--score preloaded cone-->
    <snippet file="ScoreCone.xml"/> 
    <!--drive over charging station-->
    <primitive id="DRIVE_PATH"
               pathname="RedCOOPOne1CubeSlow.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="0"
               arm="FLOOR_POSITION_ROTATE"
               extender="STARTING_POSITION_EXTEND"
               intake="INTAKE_OFF"
               time="6.0"
               />
    <!--drive picking up a cube after the charging station-->
    <primitive id="DRIVE_PATH"
               pathname="RedCOOPTwo1Slow.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="180"
               arm="FLOOR_POSITION_ROTATE"
               extender="FLOOR_EXTEND"
               intake="INTAKE"
               time="1.25"
               />
 <!--grab cube-->
<primitive id="VISION_ALIGN"
               pipeline="CUBE"
               arm="FLOOR_POSITION_ROTATE"
               extender="FLOOR_EXTEND"
               intake="INTAKE"
               time="1.0"
               />
    <!--drive onto charging station-->
    <primitive id="DRIVE_PATH"
               pathname="RedCOOPTwo2Slow.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="0"
               arm="FLOOR_POSITION_ROTATE"
               extender="STARTING_POSITION_EXTEND"
               intake="INTAKE_HOLD_CUBE"
               time="3.0"
               />
    <!--laumch cube-->
    <primitive id="AUTO_BALANCE"
               headingOption="FACE_APRIL_TAG"
               arm="CUBE_BACKROW_ROTATE"
               extender="STARTING_POSITION_EXTEND"
               intake="INTAKE_HOLD_CUBE"
               time="0.65"
               />
    <primitive id="AUTO_BALANCE"
               headingOption="FACE_APRIL_TAG"
               arm="CUBE_BACKROW_ROTATE"
               extender="STARTING_POSITION_EXTEND"
               intake="INTAKE_EXPEL"
               time="0.25"
               />
    <!--auto balance-->
    <primitive id="AUTO_BALANCE"
               headingOption="SPECIFIED_ANGLE"
               heading="0"
               arm="FLOOR_POSITION_ROTATE_AUTON"
               extender="STARTING_POSITION_EXTEND"
               intake="INTAKE_HOLD_CUBE"
               time="10.0"
               />
</auton>

=== Team302/2024Crescendo/src/main/deploy/auton/RedHPThreeNP.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>
<primitive id="RESET_POSITION_PATH_PLANNER"
	           pathname="RedHP1"
			/>
    <!--score preloaded cone-->
    <snippet file="ScoreCone.xml"/>
    <!--drive to cube-->
<primitive id="DRIVE_PATH_PLANNER"
	           pathname="RedHP1"
			   arm="FLOOR_POSITION_ROTATE_AUTON"
               intake="INTAKE_OFF"
			   extender="STARTING_POSITION_EXTEND"
               time="2.25"/>
<primitive id="DO_NOTHING"
			   arm="FLOOR_POSITION_ROTATE"
               intake="INTAKE"
			   extender="FLOOR_EXTEND"
               time="0.25"/>
<primitive id="DRIVE_PATH_PLANNER"
	           pathname="RedHP2"
			   arm="FLOOR_POSITION_ROTATE"
               intake="INTAKE"
			   extender="FLOOR_EXTEND"
               time="2.40"/>
<!--drive to scoring station-->
<primitive id="DRIVE_PATH_PLANNER"
	           pathname="RedHP3"
			   arm="FLOOR_POSITION_ROTATE"
               intake="INTAKE_HOLD_CUBE"
			   extender="STARTING_POSITION_EXTEND"
               time="3.0"/>
<!--score cube-->
        <snippet file="ScoreHighCube.xml"/>
<!--drive to cone-->
<primitive id="DRIVE_PATH_PLANNER"
	        pathname="RedHP5"
			arm="FLOOR_POSITION_ROTATE"
            intake="INTAKE"
			extender="FLOOR_EXTEND"
            time="2.85"/>
</auton>

=== Team302/2024Crescendo/src/main/deploy/auton/BluePodiumWing1Center2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>

<primitive id= "RESET_POSITION_PATH_PLANNER"
noteOption="STATE_HOLD_FEEDER"/>

<snippet file= "PodiumStart.xml"/>
<snippet file= "ShootWhenStopAuto.xml"/>

<snippet file= "PodiumCenterRing5.xml"/>

<snippet file= "ShootWhenStopAuto.xml"/>

<snippet file= "PodiumCenterRing4.xml"/>

<snippet file= "ShootWhenStopAuto.xml"/>

<snippet file= "PodiumWingRing3.xml"/>
<snippet file= "ShootWhenStopAuto.xml"/>
</auton>

=== Team302/2024Crescendo/src/main/deploy/auton/BlueAmpWing2Center0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>

<primitive id = "RESET_POSITION_PATH_PLANNER"
pathname= "BlueAmpWing2Center0.path"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BlueAmpWing2Center0.path"
time= "0.6"/>
<!--Drive closer to speaker and angle ourselves-->

<snippet file = "ShootWhenStop.xml"/>
<!--Shoot preload-->

<primitive id = "DRIVE_PATH_PLANNER"
pathname= "BlueAmpWing2Center0.path"
time= "3.0"/>
<!--Go up to ring, assumed to intake the 1.0 mark in this drive, then drive up to speaker and shoot-->

<snippet file = "ShootWhenStop.xml"/>

<primitive id = "DRIVE_PATH_PLANNER"
pathname= "BlueAmpWing2Center0.path"
time= "1.0"/>
<!--We go up to the ring in front of speaker and are assumed to intake it at this mark-->

<snippet file = "ShootWhenStop.xml"/>
<!--Shoot after intake and we are already across the line so we are done-->

</auton>

=== Team302/2024Crescendo/src/main/deploy/auton/BlueSubwooferWing2Center2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">

<auton>

<primitive id= "RESET_POSITION_PATH_PLANNER_NO_VISION"
pathname= "BlueSubwooferWing2Center2_A"/>

<snippet file= "ShootWhenStopManual.xml"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BlueSubwooferWing2Center2_A"
time= "3.0"
noteOption="STATE_FEEDER_INTAKE"/>
 
<!-- <primitive id= "DRIVE_PATH_PLANNER"
pathname= "DRIVE_TO_NOTE"
noteOption="STATE_FEEDER_INTAKE"
pathgains= "ShortPath"/> -->

<snippet file= "ShootWhenStopAuto.xml"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BlueSubwooferWing2Center2_B"
time= "3.0"
noteOption="STATE_FEEDER_INTAKE"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "DRIVE_TO_NOTE"
noteOption="STATE_FEEDER_INTAKE"
pathgains= "ShortPath"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BlueSubwooferWing2Center2_C"
time= "3.0"
noteOption="STATE_FEEDER_INTAKE"/>

<snippet file= "ShootWhenStopAuto.xml"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BlueSubwooferWing2Center2_D"
time= "3.0"
noteOption="STATE_FEEDER_INTAKE"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BlueSubwooferWing2Center2_E"
time= "3.0"
noteOption="STATE_FEEDER_INTAKE"/>

<snippet file= "ShootWhenStopAuto.xml"/>

</auton>
