=== Team302/2024Crescendo/src/main/deploy/auton/auton.dtd
<!ELEMENT auton (snippet | primitive)* >

<!ELEMENT snippet EMPTY>
<!ATTLIST snippet file CDATA #IMPLIED>

<!ELEMENT primitive EMPTY >
<!ATTLIST primitive 
          id                ( DO_NOTHING | HOLD_POSITION | DRIVE_DISTANCE | DRIVE_TIME | TURN_ANGLE_ABS | TURN_ANGLE_REL |
                              DRIVE_PATH_PLANNER | RESET_POSITION | RESET_POSITION_PATH_PLANNER | VISION_ALIGN )
                            "DO_NOTHING"
       
		  time				CDATA #IMPLIED
          distance		    CDATA "0.0"
          headingOption     CDATA "MAINTAIN"
          heading           CDATA "0.0"
          drivespeed        CDATA "0.0"
          enddrivespeed     CDATA "0.0"
          pathname          CDATA #IMPLIED
          alignmentMethod   ( ROTATE | STRAFE ) "ROTATE"
          pipeline          ( UNKNOWN | OFF | APRIL_TAG | CONE_NODE | CONE | CUBE ) "APRIL_TAG"

          noteManager       ( NOTE_MANAGER_FRONT_INTAKE | NOTE_MANAGER_BACK_INTAKE | NOTE_MANAGER_TRANSFER |
                              NOTE_MANAGER_PLACER | NOTE_MANAGER_ELEVATOR | NOTE_MANAGER_FEEDER |
                              NOTE_MANAGER_LAUNCHER_TOP | NOTE_MANAGER_LAUNCHER_BOTTOM | NOTE_MANAGER_LAUNCHER_ANGLE )
                              "MOTOR_CONTROLLER_USAGE"


          )
>

=== Team302/2024Crescendo/src/main/deploy/auton/RedPodiumWing1Center2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>

<primitive id= "RESET_POSITION_PATH_PLANNER_NO_VISION"
            pathname= "RedPodiumWing1Center2_A"
                noteOption="STATE_HOLD_FEEDER"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BluePodiumWing1Center2_1A"
time= "0.8"
noteOption="STATE_READY_AUTO_LAUNCH"/>

<snippet file= "ShootWhenStopAuto.xml"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "RedPodiumWing1Center2_A"
time= "1.2"
noteOption="STATE_FEEDER_INTAKE"/>


<primitive id="DO_NOTHING"
time="0.8"
noteOption="STATE_FEEDER_INTAKE"/>


<snippet file= "ShootWhenStopAuto.xml"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "RedPodiumWing1Center2_B"
time= "6.5"
noteOption="STATE_FEEDER_INTAKE"/>

<snippet file= "ShootWhenStopAuto.xml"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "RedPodiumWing1Center2_C"
time= "6.5"
noteOption= "STATE_FEEDER_INTAKE"/>

<snippet file= "ShootWhenStopAuto.xml"/>


</auton>

=== Team302/2024Crescendo/src/main/deploy/auton/BlueHPTwoNP.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>
<primitive id="RESET_POSITION_PATH_PLANNER"
	           pathname="BlueHP1"
			/>
    <!--score preloaded cone-->
    <snippet file="ScoreCone.xml"/>
    <!--drive to charing station-->
<primitive id="DRIVE_PATH_PLANNER"
	           pathname="BlueHP1"
			   arm="FLOOR_POSITION_ROTATE_AUTON"
               intake="INTAKE_OFF"
			   extender="STARTING_POSITION_EXTEND"
               time="2.25"/>
<primitive id="DO_NOTHING"
			   arm="FLOOR_POSITION_ROTATE"
               intake="INTAKE"
			   extender="FLOOR_EXTEND"
               time="0.35"/>
<!--drive to cone-->
<primitive id="DRIVE_PATH_PLANNER"
	           pathname="BlueHP2"
			   arm="FLOOR_POSITION_ROTATE"
               intake="INTAKE"
			   extender="FLOOR_EXTEND"
               time="3.0"/>
<!--drive to scoring station-->
<primitive id="DRIVE_PATH_PLANNER"
	           pathname="BlueHP3"
			   arm="FLOOR_POSITION_ROTATE"
               intake="INTAKE_HOLD_CUBE"
			   extender="STARTING_POSITION_EXTEND"
               time="3.0"/>
<!--score cone-->
        <snippet file="ScoreHighCube.xml"/>

<primitive id="DRIVE_PATH_PLANNER"
	           pathname="BlueHP4"
			   arm="FLOOR_POSITION_ROTATE"
               intake="INTAKE_OFF"
			   extender="STARTING_POSITION_EXTEND"
               time="3.0"/>
</auton>

=== Team302/2024Crescendo/src/main/deploy/auton/BlueAmpWing0Center2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">

<auton>
<primitive id= "RESET_POSITION_PATH_PLANNER_NO_VISION"
pathname= "BlueAmpWing0Center1_A"
noteOption="STATE_READY_AUTO_LAUNCH"/>

<snippet file= "AmpCenterStart.xml"/>

<snippet file= "ShootWhenStopAuto.xml"/>

<snippet file= "AmpCenterRing1.xml"/>

<snippet file= "ShootWhenStopAuto.xml"/>

<snippet file= "AmpCenterRing2.xml"/>

<snippet file= "ShootWhenStopAuto.xml"/>


</auton>

=== Team302/2024Crescendo/src/main/deploy/auton/BlueAmpSideWing1Center0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>

<primitive id = "RESET_POSITION_PATH_PLANNER"
pathname = "BlueAmpSideWing1Center0"/>

<primitive id = "DRIVE_PATH_PLANNER"
time = "1.55"/>

<primitive id = "ShootWhenStop.xml"/>

<primitive id = "DRIVE_PATH_PLANNER"
time = "1.45"/>

<!--Intake On-->
<primitive id = "DRIVE_PATH_PLANNER" 
time = "1.40"/>

<primitive id = "ShootWhenStop.xml"/>

<primitive id = "DRIVE_PATH_PLANNER"
time = "3.81"/>

<auton/>

=== Team302/2024Crescendo/src/main/deploy/auton/BlueHPOneP.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>
<primitive id="RESET_POSITION"
	   pathname="BlueHPOne1.wpilib.json"
               intake="INTAKE_HOLD"/>
    <!--score preloaded cone-->
    <snippet file="ScoreCone.xml"/>
    <!--drive to charing station-->
    <primitive id="DRIVE_PATH"
               pathname="BlueHPOne1.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="180"
               arm="STARTING_POSITION_ROTATE"
               intake="INTAKE_OFF"
               time="0.5"
               />
    <primitive id="DRIVE_PATH"
               pathname="BlueHPOne4.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="180"
               arm="STARTING_POSITION_ROTATE"
               intake="INTAKE_OFF"
               time="2.0"
               />
    <primitive id="DRIVE_PATH"
               pathname="BlueHPOne2.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="180"
               intake="INTAKE_OFF"
               time="5.0"
               />
    <primitive id="DRIVE_PATH"
               pathname="BlueHPOne3.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="0"
               intake="INTAKE_OFF"
               time="2.0"
               />
    <!--drive onto charging station-->
    <primitive id="DRIVE_PATH"
               pathname="BlueHPOne4Slow.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="0"
               intake="INTAKE_OFF"
               time="6.0"
               />
    <!--auto balance-->
    <primitive id="AUTO_BALANCE"
               arm="STARTING_POSITION_ROTATE"
               extender="STARTING_POSITION_EXTEND"
               intake="INTAKE_OFF"
               time="10.0"
               />
</auton>

=== Team302/2024Crescendo/src/main/deploy/auton/UnusedPaths/RedPodiumWing0Center2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>

<primitive id= "RESET_POSITION_PATH_PLANNER_NO_VISION"
           pathname="StartBluePodiumCenter"
           noteOption="STATE_READY_AUTO_LAUNCH"/>

<primitive id= "DRIVE_PATH_PLANNER"
    pathname= "StartBluePodiumCenter"
    time= "1.0"
    noteOption="STATE_READY_AUTO_LAUNCH"
    />

<snippet file= "ShootWhenStopAuto.xml"/>

<snippet file= "PodiumCenterRing5.xml"/>

<snippet file= "ShootWhenStopAuto.xml"/>

<snippet file="PodiumCenterRing4.xml"/>

<snippet file= "ShootWhenStopAuto.xml"/>

</auton>

=== Team302/2024Crescendo/src/main/deploy/auton/RedAmpWing2Center2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>

<primitive id= "RESET_POSITION_PATH_PLANNER"
pathname= "BlueAmpWing2Center2Start"
noteOption="STATE_READY_ODOMETRY_LAUNCH"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BlueAmpWing2Center2Start"
noteOption="STATE_READY_ODOMETRY_LAUNCH"
time= "1.0"/>

<snippet file= "ShootWhenStopAuto.xml"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BlueAmpWing2Center2_A"
noteOption= "STATE_FEEDER_INTAKE"
time= "2.5"
visionAligment = "SPEAKER"/>

<snippet file= "ShootWhenStopAuto.xml"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BlueAmpWing2Center2_B"
noteOption= "STATE_FEEDER_INTAKE"
time= "2.0"
pathUpdateOption = "NOTE"/>

<snippet file= "ShootWhenStopAuto.xml"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BlueAmpWing2Center2_C"
noteOption= "STATE_FEEDER_INTAKE"
time="2.0"
visionAligment = "SPEAKER"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "DRIVE_TO_NOTE"
visionAligment= "NOTE"
noteOption= "STATE_FEEDER_INTAKE"
time= "2.5"/>

<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BlueAmpWing2Center2_D"
noteOption= "STATE_READY_ODOMETRY_LAUNCH"
time= "2.5"
pathUpdateOption = "NOTE"/>

<snippet file= "ShootWhenStopAuto.xml"/>


<primitive id= "DRIVE_PATH_PLANNER"
pathname= "BlueAmpWing2Center2_E"
noteOption= "STATE_READY_ODOMETRY_LAUNCH"
time= "2.5"
pathUpdateOption = "NOTE"
visionAligment= "SPEAKER"/>

<snippet file= "ShootWhenStopAuto.xml"/>

</auton>

=== Team302/2024Crescendo/src/main/deploy/auton/BlueSubwooferWIng2Center0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">

<auton>

<primitive id = "RESET_POSITION_PATH_PLANNER"
pathname = "BlueSubwooferWing2Center0"/>

<snippet file = "ShootWhenStop.xml"/>

<primitive id = "DRIVE_PATH_PLANNER"
time = "1.50"/>

<!--Intake On-->
<primitive id = "DRIVE_PATH_PLANNER"
time = ".7"/>

<primitive id = "DRIVE_PATH_PLANNER"
time = "1.25"/>

<snippet file = "ShootWhenStop.xml"/>

<primitive id = "DRIVE_PATH_PLANNER"
time = ".40"/>

<!--Intake On-->
<primitive id = "DRIVE_PATH_PLANNER"
time = "1.10"/>

<primitive id = "DRIVE_PATH_PLANNER"
time = ".40"/>

<snippet file = "ShootWhenStop.xml"/>

<primitive id = "DRIVE_PATH_PLANNER"
time = "2.6"/>

</auton>
